version: 2.1

orbs:
  slack: circleci/slack@4.6.2
  jira: circleci/jira@1.0.6

commands:
  setvalues:
    steps: 
      - run: 
          command: |
            sudo chmod +x generate_vars.sh
            ./generate_vars.sh
          when: always

slack-fail-post-step: &slack-fail-post-step
  post-steps:
     - setvalues
     - run:
        command: |
          echo $NAME
          echo $COMMITTER_NAME
        when: always
     - persist_to_workspace:
        root: ./
        paths:
          - envars.txt
     - slack/notify:
        custom: |
          {
            "text": "",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "❌ *Failure* #${CIRCLE_BUILD_NUM} `${CIRCLE_PROJECT_REPONAME}` ,  `${CIRCLE_JOB}` executed by `${CIRCLE_USERNAME}`, name: `${NAME}`, `${COMMITTER_NAME}`"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Job"
                    },
                    "url": "${CIRCLE_BUILD_URL}"
                  }
                ]
              }
            ]
          }
        event: fail
        debug: true

     - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "✅ *Success* #${CIRCLE_BUILD_NUM}"         
                    }
                  ]
                }
              ]
            }
          event: pass

jobs:
  deploy:
    parameters:
      pass:
        type: integer
        default: 0
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: echo "deploy my app"
      - run: exit <<parameters.pass>>

  deploy2:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo "deploy my app"
      - run: cat hello

workflows:
  deploy:
    jobs:
      - deploy:
          pass: 0
          <<: *slack-fail-post-step
          context:
            - slack-secrets
      - deploy:
          pass: 1
          <<: *slack-fail-post-step
          context:
            - slack-secrets
