version: 2.1

orbs:
  slack: circleci/slack@4.6.2
  jira: circleci/jira@1.0.6

commands:
  setvalues:
    steps: 
      - run: 
          command: |
            sudo chmod +x generate_vars.sh
            ./generate_vars.sh
          when: always

slack-fail-post-step: &slack-fail-post-step
  post-steps:
     - setvalues
     - run:
        command: |
          echo 'export SLACK_TEMPLATE_PASS=$(cat ./templates/passing.json)' >> $BASH_ENV
          echo 'export SLACK_TEMPLATE_FAIL=$(cat ./templates/failing.json)' >> $BASH_ENV
        when: always
     - persist_to_workspace:
        root: ./
        paths:
          - envars.txt
     - slack/notify:
        template: SLACK_TEMPLATE_FAIL
        event: fail
        debug: true

     - slack/notify:
        template: SLACK_TEMPLATE_PASS
        event: pass

jobs:
  deploy:
    parameters:
      pass:
        type: integer
        default: 0
    docker:
      - image: 'cimg/base:edge'
    steps:
      - checkout
      - run: echo "deploy my app"
      - run: exit <<parameters.pass>>

workflows:
  deploy:
    jobs:
      - deploy:
          pass: 0
          <<: *slack-fail-post-step
          context:
            - slack-secrets
      - deploy:
          pass: 1
          <<: *slack-fail-post-step
          context:
            - slack-secrets
